app:
    resource: '@AppBundle/Controller/'
    type: annotation
home:
    path:     /home
    defaults: { _controller: 'TelaPrincipal::home' }
admin:
    path:     /admin
    defaults: { _controller: 'CadastroGrupos::admin' }