AppBundle\Entity\Categoriasdoacoes:
    type: entity
    table: categoriasdoacoes
    id:
        idcategoriasdoacoes:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: idCategoriasDoacoes
            generator:
                strategy: IDENTITY
    fields:
        nomecategoria:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
            column: nomeCategoria
        nomesubcategoria:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: nomeSubCategoria
        outro:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
    lifecycleCallbacks: {  }
