AppBundle\Entity\Grupos:
    type: entity
    table: grupos
    indexes:
        fk_Grupos_Usuarios1_idx:
            columns:
                - idUsuario
    uniqueConstraints:
        idGrupos_UNIQUE:
            columns:
                - idGrupos
    id:
        idgrupos:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: idGrupos
            generator:
                strategy: IDENTITY
    fields:
        nomegrupo:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
            column: nomeGrupo
        telefoneresponsavel:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
            column: telefoneResponsavel
        numerointegrantes:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: numeroIntegrantes
    manyToOne:
        idusuario:
            targetEntity: Usuarios
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idUsuario:
                    referencedColumnName: idUsuario
            orphanRemoval: false
    lifecycleCallbacks: {  }
